deployment:
  enabled: true  
  name: sharks
  container:
    name: sharks
    port: 8081
  replica: 2

image:
  name: itsmrhashtag/sharks-test
  tag: 20250328092624
  pullSecrets:
    - name: my-registry-secret

service:
  name: sharks-service
  type: NodePort
  port: 8081
  targetPort: 8081
  nodePort: 30004
