name: Docker Build and Helm Chart Update

on:
  push:
    branches:
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sharks-test .

      - name: Generate a new Docker tag
        id: tag
        run: |
          NEW_TAG=$(date +'%Y%m%d%H%M%S')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Generated new Docker image tag: $NEW_TAG"

      - name: Tag Docker image
        run: |
          docker tag sharks-test ${{ secrets.DOCKER_USERNAME }}/sharks-test:$NEW_TAG
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sharks-test:$NEW_TAG

      - name: Trigger workflow to update values.yaml with new image tag
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"ref": "refs/heads/master", "inputs": {"tag": "'${{ env.NEW_TAG }}'"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-values.yaml/dispatches