name: Docker Build and Helm Chart Update

on:
  push:
    branches:
      - master
      - task02  
    paths:
      - Dockerfile  
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile  

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sharks-test .

      - name: Generate a new Docker tag
        id: tag
        run: |
          NEW_TAG=$(date +'%Y%m%d%H%M%S')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Generated new Docker image tag: $NEW_TAG"

      - name: Tag Docker image
        run: |
          docker tag sharks-test ${{ secrets.DOCKER_USERNAME }}/sharks-test:$NEW_TAG
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sharks-test:$NEW_TAG

      - name: Update helm values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: $NEW_TAG/" values.yaml
          
      - name: Commit and push the updated values.yaml
        run: |
          git config --global user.email "pushprajkushwaha@gmail.com"
          git config --global user.name "pushprajkushwaha"
          git add values.yaml
          git commit -m "Update Docker image tag to $NEW_TAG in values.yaml"
          git branch
          cat .git/HEAD
          git push origin task02

